name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@main"
        with:
            target-repo: "anolilab/semantic-release"
            issue-welcome: >
                It looks like this is your first issue. Welcome! ðŸ‘‹
                One of the project maintainers will be with you as soon as possible. We
                appreciate your patience. To safeguard the health of the project, please
                take a moment to read our [code of conduct](https://github.com/anolilab/semantic-release/blob/main/.github/CODE_OF_CONDUCT.md).
            pr-welcome: >
                It looks like this is your first pull request. ðŸŽ‰
                Thank you for your contribution! One of the project maintainers will triage
                and assign the pull request for review. We appreciate your patience. To
                safeguard the health of the project, please take a moment to read our
                [code of conduct](https://github.com/anolilab/semantic-release/blob/main/.github/CODE_OF_CONDUCT.md).
            pr-merged: >
                Congratulations on your first merged pull request! ðŸŽ‰
                Thank you for your contribution!
                We appreciate your patience.
                We look forward to your next contribution.
