# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "reopened"
            - "edited"
            - "synchronize"
    merge_group: # yamllint disable-line rule:empty-values

permissions:
    contents: "read"

jobs:
    semantic-pull-request:
        permissions:
            pull-requests: "write" # to analyze PRs (amannn/action-semantic-pull-request)
            statuses: "write" # to mark status of analyzed PR (amannn/action-semantic-pull-request)
        runs-on: "ubuntu-latest"
        name: "Semantic Pull Request"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4" # v2.7.1
              with:
                  egress-policy: "audit"

            - name: "Validate PR title"
              id: "lint_pr_title"
              uses: "amannn/action-semantic-pull-request@cfb60706e18bc85e8aec535e3c577abe8f70378e" # v5.5.2
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              with:
                  types: |
                      build
                      chore
                      ci
                      docs
                      feat
                      fix
                      perf
                      infra
                      refactor
                      revert
                      test

            - uses: "marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31" # v2.9.0
              # When the previous steps fail, the workflow would stop. By adding this
              # condition you can continue the execution with the populated error message.
              if: "always() && (steps.lint_pr_title.outputs.error_message != null)"
              with:
                  header: "pr-title-lint-error"
                  message: |
                      Hey there and thank you for opening this pull request! üëãüèº

                      We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

                      Details:

                      ```
                      ${{ steps.lint_pr_title.outputs.error_message }}
                      ```

              # Delete a previous comment when the issue has been resolved
            - if: "${{ steps.lint_pr_title.outputs.error_message == null }}"
              uses: "marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31" # v2.9.0
              with:
                  header: "pr-title-lint-error"
                  message: |
                      Thank you for following the naming conventions! üôè
